eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: machines-app
          uri: http://localhost:8081
          predicates:
            - Path=/machines/**

  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8222
